[tool.poetry]
name = "sprue-search"
version = "0.1.0"
description = "Sprue searcher Project."
authors = ["traindropper"]
license = "GPLv3"

[tool.poetry.dependencies]
python = "^3.8"
cv2 = "^4.12.0.88"

[tool.poetry.dev-dependencies]
pytest = "^6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"