[project]
name = "sprue-search"
version = "0.1.0"
description = "Sprue searcher Project."
authors = ["traindropper"]
license = "GPL-3.0-or-later"
readme = "README.md"

requires-python = ">=3.13"

dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.3.2",
    "opencv-contrib-python>=4.11.0.86", # cv2, apt-get install libgl1
    "pytesseract>=0.3.13", # apt-get install tesseract-ocr
]
